### ISSUE TITLE
Issue #1 Forecast temperature data will not load

### ISSUE THREAD

**Issue by SandSux** [SandSux/SciFi_Conky_HUD#1]
**File**
 `weather.rc`

**Issue**
 'Daily' temperature loads, updates, and displays current temperature data; However, Forecast temperature data will not load. Suspect flaw in openweathermap API.

**Comment by Guyverix** [comment]
Not the API.  It is what jq is parsing.
jq .list[2].main.temp_max ~/.cache/forecast.json works..

This is in the rc file: 
jq .list[2].temp.max ~/.cache/forecast.json 

It is the same behavior for the minimum temps as well.
jq .list[1].main.temp_min ~/.cache/forecast.json
vs
 jq .list[1].temp.min ~/.cache/forecast.json

**Comment by SandSux** [comment]
**SOLVED**
