### ISSUE TITLE
Missing directory anim4 for video2.rc

### ISSUE THREAD

**Issue by Guyverix** [SandSux/SciFi_Conky_HUD#2]
video2.rc has several png files defined...
~/.conky/images/anim4/11.png
The directory did not make it into the repo.

**Comment by SandSux** [comment]
Video2 is user defined. I did not add it as it is a personal preference as to what you wish to add. I will document this. I didn't bother defining it on my machine. You can put together whatever "video" you'd like for this config.

**Comment by Guyverix** [comment]
Ah, gotcha!  Thank you!  I just got the last little pieces working on my work desktop machine.  This is great!
