### ISSUE TITLE
Minor bug / error with user.rc

### ISSUE THREAD

**Issue by Guyverix** [SandSux/SciFi_Conky_HUD#3]
Do not feel comfortable making a pull request since I am still debugging to get this perfect on my system.  Wanted to let you know that there is a minor issue with the user.rc file at least on the Ubuntu Conky build.  The alignment = top_left using single quotes appears to break the configuration. 

It was putting it at the bottom of the screen until I removed  the quotes:
Works: alignment = top_left, 
Errors in Ubuntu XFCE: alignment = 'top_left',

**Comment by SandSux** [comment]
I changed my user.rc, removing the ' ' from  " 'top_left' " to test your issue and it did in fact break that configuration on my machine: Ubuntu Mate 16.04. I am going to leave that portion of the configuration untouched. Thank you nonetheless for your support

**Comment by Guyverix** [comment]
Since it is likely the way my conky was compiled, I will close this out.
